config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do
  
  devise_for :users,
    :path => '',
    :path_names => {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'signup'
    },
    :controllers => {
      :sessions => "users/sessions",
      :registrations => "users/registrations",
      :confirmations => "users/confirmations",
    }

  # Sidekiq
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  username == "admin" && password == "password"
  end if Rails.env.production? || Rails.env.staging?
  mount Sidekiq::Web, at: "/sidekiq"

  root to: 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_raven_context

  private

  def set_raven_context
    Raven.user_context(id: session[:current_user_id]) # or anything else in session
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

  private

  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    root_path
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :configure_permitted_parameters

  def destroy
    super
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password) }
  end

  def after_sign_up_path_for(resource)
    flash[:success] = "We have sent a confirmation email to your inbox. Verify your email address to get started."
    root_path 
  end

  def after_inactive_sign_up_path_for(resource)
    flash[:success] = "We have sent a confirmation email to your inbox. Verify your email address to get started."
    root_path
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def new
    super
  end

  protected

  def after_sign_in_path_for(resource)
    flash[:success] = "Welcome back #{resource.first_name}!"
    root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% page_title = @page_title ? "#{@page_title} - #{ENV['APP_NAME']}" : "#{ENV['APP_NAME']} - #{ENV['APP_DESCRIPTION']}" %>
    <title><%= page_title %></title>

    <link rel="shortcut icon" type="image/png" href="/favicon.png"/>
    <link rel="apple-touch-icon" href="/favicon.png"/>

    <!-- Viewport meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="apple-mobile-web-app-title" content="<%= ENV['APP_NAME'] %>">

    <!-- OpenGraph Meta -->
    <meta property="og:site_name" content="<%= ENV['APP_NAME'] %>"/>
    <meta property="og:type" content="website"/>
    <meta property="og:description" content="<%= ENV['APP_DESCRIPTION'] %>"/>
    <meta property="og:url" content="<%= ENV['APP_URL'] %>"/>
    <meta property="og:title" content="<%= page_title %>"/>
    <meta property="og:image" content="<%= ENV['APP_IMAGE'] %>"/>

    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="<%= ENV['TWITTER'] %>" />
    <meta name="twitter:title" content="<%= page_title %>" />
    <meta name="twitter:description" content="<%= ENV['APP_DESCRIPTION'] %>" />
    <meta name="twitter:image" content="<%= ENV['APP_IMAGE'] %>" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/scripts/ga' %>

  </head>

  <body>
    <%= yield %>

    <%= render 'layouts/scripts/flash' %>
    <%= yield :extra_scripts %>
  </body>
</html>

app/views/layouts/scripts/_flash.html.erb
<script type="text/javascript">
<% if flash[:success] %>
  showSuccess("<%= flash[:success] %>");
<% end %>
<% if flash[:notice] %>
  showNotice("<%= flash[:notice] %>");
<% end %>
<% if flash[:warning] %>
  showWarning("<%= flash[:warning] %>");
<% end %>
<% if flash[:error] %>
  showError("<%= flash[:error] %>");
<% end %>
</script>

app/views/layouts/scripts/_form_errors.html.erb
<% if obj.errors.any? %>
  <script type="text/javascript">
    showError("<%= j render(:partial => 'layouts/scripts/validation', :locals => {:obj => obj}) %>")
  </script>
<% end %>

app/views/layouts/scripts/_ga.html.erb
<% if (analytics = ENV['GA_ID']).present? %>
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%= analytics %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', '<%= analytics %>');

    document.addEventListener('turbolinks:load', event => {
    if (typeof gtag === 'function') {
      gtag('config', '<%= analytics %>', {
        'page_location': event.data.url
      });
    }
  });
  </script>
<% end %>

app/views/layouts/scripts/_validation.html.erb
<% if obj.errors.any? %>
  <div class="error_explanation">
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/pages/home.html.erb
<section class="hero is-primary is-medium is-bold">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Welcome!
      </h1>
      <h2 class="subtitle">
        This is a <a href="https://github.com/ManuelFrigerio/rails-blueprint" target="_blank" class="has-text-grey-dark">Rails 5 app boilerplate</a> by <a href="https://manuel.friger.io" target="_blank" class="has-text-grey-dark ">Manuel Frigerio</a>
      </h2>
      <%= link_to "Signup", new_user_registration_path, class: "button is-primary is-rounded is-inverted is-outlined" %>
      <%= link_to "Login", new_user_session_path, class: "button is-primary is-rounded is-inverted is-outlined" %>
    </div>
  </div>
</section>

<% if user_signed_in? %>
<section class="section">
    <div class="container">
      <p><%= link_to "Log out".html_safe, destroy_user_session_path, method: :delete, class: "has-text-danger" %></p>
    </div>
  </section>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "has-text-grey" %> •
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "has-text-grey" %> •
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "has-text-grey" %> •
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation email?", new_confirmation_path(resource_name), class: "has-text-grey" %>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "has-text-grey" %> •
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "has-text-grey" %> •
  <% end -%>
<% end -%>